Organizations:

    - &OrdererOrg
        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/aalaa.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"

    - &Ibm
        Name: IbmMSP

        ID: IbmMSP

        MSPDir: crypto-config/peerOrganizations/ibm.aalaa.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('IbmMSP.admin', 'IbmMSP.peer', 'IbmMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('IbmMSP.admin', 'IbmMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('IbmMSP.admin')"

        AnchorPeers:
            - Host: peer0.ibm.aalaa.com
              Port: 7051

    - &Hsbc
        Name: HsbcMSP

        ID: HsbcMSP

        MSPDir: crypto-config/peerOrganizations/hsbc.aalaa.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('HsbcMSP.admin', 'HsbcMSP.peer', 'HsbcMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('HsbcMSP.admin', 'HsbcMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('HsbcMSP.admin')"

        AnchorPeers:
            - Host: peer0.hsbc.aalaa.com
              Port: 9051

    - &Cib
        Name: CibMSP

        ID: CibMSP

        MSPDir: crypto-config/peerOrganizations/cib.aalaa.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CibMSP.admin', 'CibMSP.peer', 'CibMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CibMSP.admin', 'CibMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CibMSP.admin')"

        AnchorPeers:
            - Host: peer0.cib.aalaa.com
              Port: 11051

Capabilities:
    Channel: &ChannelCapabilities
        V1_3: true

    Orderer: &OrdererCapabilities
        V1_1: true

    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: false
        V1_1: false

Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    OrdererType: solo

    Addresses:
        - orderer.aalaa.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities

Profiles:

    ThreeOrgsOrdererGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Ibm
                    - *Hsbc
                    - *Cib
    ThreeOrgsChannel:
        Consortium: SampleConsortium
        <<: *ChannelDefaults
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Ibm
                - *Hsbc
                - *Cib
            Capabilities:
                <<: *ApplicationCapabilities

    SampleDevModeKafka:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: kafka
            Kafka:
                Brokers:
                - kafka.aalaa.com:9092

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Ibm
                - *Hsbc
                - *Cib

    SampleMultiNodeEtcdRaft:
        <<: *ChannelDefaults
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            OrdererType: etcdraft
            EtcdRaft:
                Consenters:
                - Host: orderer.aalaa.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer.aalaa.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer.aalaa.com/tls/server.crt
                - Host: orderer2.aalaa.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer2.aalaa.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer2.aalaa.com/tls/server.crt
                - Host: orderer3.aalaa.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer3.aalaa.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer3.aalaa.com/tls/server.crt
                - Host: orderer4.aalaa.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer4.aalaa.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer4.aalaa.com/tls/server.crt
                - Host: orderer5.aalaa.com
                  Port: 7050
                  ClientTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer5.aalaa.com/tls/server.crt
                  ServerTLSCert: crypto-config/ordererOrganizations/aalaa.com/orderers/orderer5.aalaa.com/tls/server.crt
            Addresses:
                - orderer.aalaa.com:7050
                - orderer2.aalaa.com:7050
                - orderer3.aalaa.com:7050
                - orderer4.aalaa.com:7050
                - orderer5.aalaa.com:7050

            Organizations:
            - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities
        Application:
            <<: *ApplicationDefaults
            Organizations:
            - <<: *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                - *Ibm
                - *Hsbc
                - *Cib
