# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.aalaa.com:
  peer0.ibm.aalaa.com:
  peer1.ibm.aalaa.com:
  peer0.hsbc.aalaa.com:
  peer1.hsbc.aalaa.com:
  peer0.cib.aalaa.com:
  peer1.cib.aalaa.com:
  c0.ibm.aalaa.com:
  c1.hsbc.aalaa.com:
  c2.cib.aalaa.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ibm
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ibm.aalaa.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ibm.aalaa.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ibm.aalaa.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: c0.ibm.aalaa.com
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hsbc
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hsbc.aalaa.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hsbc.aalaa.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hsbc.aalaa.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: c1.hsbc.aalaa.com
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca:1.4
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-cib
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.cib.aalaa.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.cib.aalaa.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/cib.aalaa.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: c2.cib.aalaa.com
    networks:
      - byfn

  orderer.aalaa.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.aalaa.com
    container_name: orderer.aalaa.com
    networks:
      - byfn

  peer0.ibm.aalaa.com:
    container_name: peer0.ibm.aalaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ibm.aalaa.com
    networks:
      - byfn

  peer1.ibm.aalaa.com:
    container_name: peer1.ibm.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ibm.aalaa.com
    networks:
      - byfn

  peer0.hsbc.aalaa.com:
    container_name: peer0.hsbc.aalaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hsbc.aalaa.com
    networks:
      - byfn

  peer1.hsbc.aalaa.com:
    container_name: peer1.hsbc.aalaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hsbc.aalaa.com
    networks:
      - byfn

  peer0.cib.aalaa.com:
    container_name: peer0.cib.aalaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.cib.aalaa.com
    networks:
      - byfn

  peer1.cib.aalaa.com:
    container_name: peer1.cib.aalaa.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.cib.aalaa.com
    networks:
      - byfn
