# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  peer0.nbe.aalaa.com:
  peer1.nbe.aalaa.com:
  c3.nbe.aalaa.com:

networks:
  byfn:

services:

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-nbe
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.nbe.aalaa.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.nbe.aalaa.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/ -b admin:adminpw -d'
    volumes:
      - ./org4-artifacts/crypto-config/peerOrganizations/nbe.aalaa.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: c3.nbe.aalaa.com
    networks:
      - byfn

  peer0.nbe.aalaa.com:
    container_name: peer0.nbe.aalaa.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.nbe.aalaa.com
      - CORE_PEER_ADDRESS=peer0.nbe.aalaa.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.nbe.aalaa:13052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.nbe.aalaa.com:14051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.nbe.aalaa.com:13051
      - CORE_PEER_LOCALMSPID=NbeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./org4-artifacts/crypto-config/peerOrganizations/nbe.aalaa.com/peers/peer0.nbe.aalaa.com/msp:/etc/hyperledger/fabric/msp
        - ./org4-artifacts/crypto-config/peerOrganizations/nbe.aalaa.com/peers/peer0.nbe.aalaa.com/tls:/etc/hyperledger/fabric/tls
        - peer0.nbe.aalaa.com:/var/hyperledger/production
    ports:
      - 13051:3051
    networks:
      - byfn

  peer1.nbe.aalaa.com:
    container_name: peer1.nbe.aalaa.com
    extends:
      file: base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.nbe.aalaa.com
      - CORE_PEER_ADDRESS=peer1.nbe.aalaa.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer1.nbe.aalaa.com:14052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.nbe.aalaa.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.nbe.aalaa.com:14051
      - CORE_PEER_LOCALMSPID=NbeMSP
    volumes:
        - /var/run/:/host/var/run/
        - ./nbe-artifacts/crypto-config/peerOrganizations/nbe.aalaa.com/peers/peer1.nbe.aalaa.com/msp:/etc/hyperledger/fabric/msp
        - ./nbe-artifacts/crypto-config/peerOrganizations/nbe.aalaa.com/peers/peer1.nbe.aalaa.com/tls:/etc/hyperledger/fabric/tls
        - peer1.nbe.aalaa.com:/var/hyperledger/production
    ports:
      - 14051:4051
    networks:
      - byfn


  Nbecli:
    container_name: nbecli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=nbecli
      - CORE_PEER_ADDRESS=peer0.nbe.aalaa.com:13051
      - CORE_PEER_LOCALMSPID=NbeMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nbe.aalaa.com/peers/peer0.nbe.aalaa.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nbe.aalaa.com/peers/peer0.nbe.aalaa.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nbe.aalaa.com/peers/peer0.nbe.aalaa.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/nbe.aalaa.com/users/Admin@nbe.aalaa.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./nbe-artifacts/crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./crypto-config/peerOrganizations/ibm.aalaa.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/ibm.aalaa.com
        - ./crypto-config/peerOrganizations/hsbc.aalaa.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hsbc.aalaa.com
        - ./crypto-config/peerOrganizations/cib.aalaa.com:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/cib.aalaa.com
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
    depends_on:
      - peer0.nbe.aalaa.com
      - peer1.nbe.aalaa.com
    networks:
      - byfn
